# Generated by Django 4.1.2 on 2023-04-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trying',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
