# Generated by Django 4.1.2 on 2022-10-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discounted_price',
            field=models.IntegerField(default=True),
        ),
    ]
