# Generated by Django 4.1.2 on 2022-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dicount',
            field=models.IntegerField(blank=True),
        ),
    ]
