# Generated by Django 4.1.2 on 2022-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_dicount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dicount',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
