# Generated by Django 4.1.2 on 2022-10-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_dicount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dicount',
            field=models.IntegerField(),
        ),
    ]
